services:
  - type: web
    name: barber-uz-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/pgserver.js
    envVars:
      - key: DATABASE_URL
        sync: false
